### PR TITLE
fixes an error with the signup

### PR DESCRIPTION
**Pull request by juliancoleman**
@jadengore fixed it

### CODE REVIEW

**Comment by juliancoleman** [comment]
wow... login was not supposed to be included here

**Comment by ebramanti** [comment]
@juliancoleman Your commit message does not match up with the actual changes, is there any way you could clean up your commit to better reflect that?

Edit: Lol started writing this before your respone.

**Comment by juliancoleman** [comment]
yeah.. just have to remove login.html... otherwise, everything here fixes it

**Comment by ebramanti** [comment]
@juliancoleman I was able to fix your history. :shipit: and continue your login work on `feature/login`.

**Pull request merged**
